Repository GSG-FC03/Art-Galary-Team3, pull requests merged in 2021-06, with the labels that each got.

#2 creating-file-structre
  images/Rectangle (1).png
  images/Rectangle (2).png
  images/Rectangle.png
  images/cover.png
  index/detail.html
  index/gallary.html
  index/single.html
  style/style.css
Labels: awaiting-reveiw‏

#4 photos-uploaded
  images/Art gallery.zip
  images/Rectangle (1).png
  images/Rectangle (2).png
  images/Rectangle (3).png
  images/Rectangle 2.3.png
  images/Rectangle 2.png
  images/Rectangle 3.png
  images/Rectangle.png
  images/Rectangle@2x.png
  images/cover.png
Labels: Done

#7 uplading images
  images/Art gallery.zip
  images/Rectangle (1).png
  images/Rectangle (2).png
  images/Rectangle (3).png
  images/Rectangle 2.3.png
  images/Rectangle 2.png
  images/Rectangle 3.png
  images/Rectangle.png
  images/Rectangle@2x.png
  images/WYN.svg
  images/bottom image.svg
  images/corner image.svg
  images/cover.png
  images/cover.svg
  images/first image.svg
  images/last images.svg
  images/mini cover.svg
  images/second image.svg
  images/third images.svg
Labels: to do

#9 Added two images to images file
  images/glasses.svg
  images/moon.svg
Labels: Done

#6 5 create header
  index/gallary.html
  style/style.css
Labels: awaiting-reveiw‏, request-change

#10 5-create-section-gallery
  index/gallary.html
  style/style.css
Labels: Done

#13 creating section row gallery
  images/New-Button.svg
  images/campass.svg
  images/pen.svg
  images/profile.svg
  images/squre.svg
  index/gallary.html
  style/style.css
Labels: Done

#12 creating cover and back-btn and vector-btn
  images/Vector.svg
  images/back.svg
  index/single.html
  style/style.css
Labels: Done

#19 19 create detail header
  images/Player1.png
  index/detail.html
  style/detailstyle.css
  style/style.css
Labels: awaiting-reveiw‏

#20 18 update single page
  index/gallary.html
  index/single.html
  style/singleStyle.css
  style/style.css
Labels: Done

#21 Update the content of readme page
  README.md
Labels: awaiting-reveiw‏

#22 update gallary page and it's style
  index/gallary.html
  style/style.css
Labels: Done

#24 update linkes pages
  index/gallary.html
  index/single.html
Labels: awaiting-reveiw‏
